/**
 * Auto-generated by scripts/upload-resource-zips.mjs
 * Do not edit by hand — run: npm run upload:resource-zips
 */
export const RESOURCE_ZIP_CLOUDINARY_URLS: Record<string, string> = {
  "Files/Branding Guidelines.zip": "https://res.cloudinary.com/dkomq1g9z/raw/upload/v1779085661/checkmate-studios/resource-zips/Branding_Guidelines.zip",
  "Files/Gradients.zip": "https://res.cloudinary.com/dkomq1g9z/raw/upload/v1779085663/checkmate-studios/resource-zips/Gradients.zip",
  "Files/Micrographics Templates.zip": "https://res.cloudinary.com/dkomq1g9z/raw/upload/v1779085666/checkmate-studios/resource-zips/Micrographics_Templates.zip",
  "Files/Proposal Template.zip": "https://res.cloudinary.com/dkomq1g9z/raw/upload/v1779085669/checkmate-studios/resource-zips/Proposal_Template.zip",
  "Files/Textures.zip": "https://pub-9f5405a27d4843fdb75ec5e3ccacc920.r2.dev/resource-zips/Files/Textures.zip",
  "Files/VHS Textures.zip": "https://pub-9f5405a27d4843fdb75ec5e3ccacc920.r2.dev/resource-zips/Files/VHS%20Textures.zip"
};
